baseURL: "http://localhost:1313/"
theme: "toha"
title: "ProgOwer"

# Multi Languages Support
languageCode: "fr-fr"
defaultContentLanguage: fr

outputs:
  home:
  - HTML
  - RSS
  - JSON

# Plugins
enableEmoji: true
