---
version: '3.6'

services:
  progower-dev:
    container_name: '${PROGOWER_NAME}-dev'
    image: ${PROGOWER_IMG}:${PROGOWER_VERSION_DEV}
    build:
      context: .
      dockerfile: Dockerfile.dev
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:1313"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 10s
    volumes:
    - ./src:/src:rw
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
    - 1313:1313
    restart: unless-stopped
